### ISSUE TITLE
 PHP User Error – yii\base\ErrorException 

### ISSUE THREAD

**Issue by AndreyThunder** [AndreyThunder/basic#3]
Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'The directory does not exist: /var/www/html/web/assets'

in /home/andrew/projects/basic/vendor/yiisoft/yii2/web/AssetManager.php:213

**Comment by AndreyThunder** [comment]
sudo chown -R www-data:andrew web/assets/

**Comment by AndreyThunder** [comment]
Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'The directory is not writable by the Web process: /var/www/html/web/assets'

in /home/andrew/projects/basic/vendor/yiisoft/yii2/web/AssetManager.php:215

**Comment by AndreyThunder** [comment]
sudo chown -R www-data:andrew web/assets/

**Comment by faridlesosibirsk** [comment]
sudo mkdir /var/www/html/web/assets
sudo chown -R www-data:andrew web/assets/
